org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchmentMinecraftVersion=1.21.1
parchmentMappingsVersion=2024.11.17

minecraftVersion=1.21.1

minecraftVersionRange=[1.21.1, 1.22)
neoVersion=21.1.90
neoVersionRange=[21.1.0,)
loaderVersionRange=[4,)

modId=libraomni
modGroup=dev.jackraidenph
modName=Libra Omni
modLicense=All Rights Reserved
modVersion=1.0.0
modAuthors=JackRaidenPH
modDescription=

uuid=ba07a43a763e47a9a2600cb88e59e197
username=JackRaidenPH